added windres and ranlib mingw in configure file

diff --git a/tcl8.5.9/win/configure b/tcl8.5.9/win/configure
--- a/tcl8.5.9/win/configure
+++ b/tcl8.5.9/win/configure
@@ -8,7 +8,8 @@
 ## --------------------- ##
 ## M4sh Initialization.  ##
 ## --------------------- ##
-
+windres_var=x86_64-w64-mingw32-windres
+ranlib_var=x86_64-w64-mingw32-ranlib
 # Be Bourne compatible
 if test -n "${ZSH_VERSION+set}" && (emulate sh) >/dev/null 2>&1; then
   emulate sh
@@ -2811,8 +2812,8 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-    # Extract the first word of "ranlib", so it can be a program name with args.
-set dummy ranlib; ac_word=$2
+    # Extract the first word of "$ranlib_var", so it can be a program name with args.
+set dummy $ranlib_var; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_RANLIB+set}" = set; then
@@ -2828,7 +2829,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_RANLIB="ranlib"
+    ac_cv_prog_RANLIB="$ranlib_var"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -2846,8 +2847,8 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-    # Extract the first word of "windres", so it can be a program name with args.
-set dummy windres; ac_word=$2
+    # Extract the first word of "$windres_var", so it can be a program name with args.
+set dummy $windres_var; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_RC+set}" = set; then
@@ -2863,7 +2864,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_RC="windres"
+    ac_cv_prog_RC="$windres_var"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -2888,13 +2889,13 @@ echo "$as_me: error: Required archive tool 'ar' not found on PATH." >&2;}
    { (exit 1); exit 1; }; }
     fi
     if test "${RANLIB}" = "" ; then
-	{ { echo "$as_me:$LINENO: error: Required archive index tool 'ranlib' not found on PATH." >&5
-echo "$as_me: error: Required archive index tool 'ranlib' not found on PATH." >&2;}
+	{ { echo "$as_me:$LINENO: error: Required archive index tool '$ranlib_var' not found on PATH." >&5
+echo "$as_me: error: Required archive index tool '$ranlib_var' not found on PATH." >&2;}
    { (exit 1); exit 1; }; }
     fi
     if test "${RC}" = "" ; then
-	{ { echo "$as_me:$LINENO: error: Required resource tool 'windres' not found on PATH." >&5
-echo "$as_me: error: Required resource tool 'windres' not found on PATH." >&2;}
+	{ { echo "$as_me:$LINENO: error: Required resource tool '$windres_var' not found on PATH." >&5
+echo "$as_me: error: Required resource tool '$windres_var' not found on PATH." >&2;}
    { (exit 1); exit 1; }; }
     fi
 fi
@@ -3859,9 +3860,9 @@ fi
 
     SHLIB_SUFFIX=".dll"
 
-    # Check for a bug in gcc's windres that causes the
+    # Check for a bug in gcc's $windres_var that causes the
     # compile to fail when a Windows native path is
-    # passed into windres. The mingw toolchain requires
+    # passed into $windres_var. The mingw toolchain requires
     # Windows native paths while Cygwin should work
     # with both. Avoid the bug by passing a POSIX
     # path when using the Cygwin toolchain.
@@ -3872,8 +3873,8 @@ fi
 	echo "101 \"name\"" >> $conftest
 	echo "END" >> $conftest
 
-	echo "$as_me:$LINENO: checking for Windows native path bug in windres" >&5
-echo $ECHO_N "checking for Windows native path bug in windres... $ECHO_C" >&6
+	echo "$as_me:$LINENO: checking for Windows native path bug in $windres_var" >&5
+echo $ECHO_N "checking for Windows native path bug in $windres_var... $ECHO_C" >&6
 	cyg_conftest=`$CYGPATH $conftest`
 	if { ac_try='$RC -o conftest.res.o $cyg_conftest'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
